ecommerce_project/cart/urls.py
from django.urls import path
from . import views
app_name='cart'
urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),
]

ecommerce_project/ecommerce_app/urls.py
from django.urls import path
from . import views

app_name='ecommerce_app'

urlpatterns = [

    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.proDetail,name='pro_category')
]

ecommerce_project/ecommerce_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('ecommerce_app.urls')),
    path('search_app/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce_project/search_app/urls.py
from django.urls import path
from . import views

app_name='search_app'
urlpatterns=[
    path('',views.SearchResult,name='SearchResult'),
]

ecommerce_project/cart/models.py
from django.db import models
from ecommerce_app.models import Product
# Create your models here.

class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return  self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecommerce_project/ecommerce_app/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('ecommerce_app:products_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('ecommerce_app:pro_category', args=[self.category.slug, self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

ecommerce_project/search_app/models.py
from django.db import models

# Create your models here.

ecommerce_project/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ecommerce_app.models import Product
from . models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
def cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=cart_id(request))

    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=cart_id(request))
        cart.save()

    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity+=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity= 1,
            cart= cart,

        )
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):

    try:
        cart=Cart.objects.get(cart_id=cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total+=(cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecommerce_project/ecommerce_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Product, Category
from django.core.paginator import Paginator, EmptyPage, InvalidPage


# Create your views here.
def allProdCat(request, c_slug=None):
    c_page = None
    product_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)\

        product_list = Product.objects.all().filter(category=c_page, available=True)

    else:
        product_list = Product.objects.all().filter(available=True)

    paginator = Paginator(product_list, 6)
    try:
        page = int(request.GET.get('page', '1',))
    except:
        page = 1

    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request, 'category.html', {'products': products, 'category': c_page})


def proDetail(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'product': product})

ecommerce_project/search_app/views.py
from django.shortcuts import render
from ecommerce_app.models import Product
from django.db.models import Q

def SearchResult(request):
    query=None
    products=None

    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))

    return render(request,'search.html',{'query':query,'products':products})

ecommerce_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/928bab6617.js" crossorigin="anonymous"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">

    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

    {% include 'header.html' %}

    {% block content %}
    {% endblock %}


<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
<footer class="bg-body-tertiary text-center text-lg-start mt-5">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2023 Copyright:
    <a class="text-body" href="#">SUHAILMK.in</a>
  </div>
  <!-- Copyright -->
</footer>

</html>

ecommerce_project/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

      this is cart page
{% endblock %}
{% block title %}
        cart-LULU
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my-title">Your Shoping Cart is empty</h1><br>
        <p class="text-center">Plese ClIck<a href="{% url 'ecommerce_app:allProdCat' %}">Here</a>to continue shoping</p>

    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my-title">Your Shopping Cart</h1>
        <br>

    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_table">
            <thead class="my_table_head">
            <tr>
                <th colspan="5">
                    Your items
                </th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="{{cart_item.product.get.absolute_url}}"><img style="height:100px;width:100px;" src="{{cart_item.product.image.url}}" class="float-left rounded custom_image"></a>
                </td>
                <td class="text-left">
                    {{cart_item.product.name}}
                    <br>
                    SKU: {{cart_item.product.id}}
                    <br>
                    Price: $ {{cart_item.product.price}}
                    <br>
                    Qty: {{cart_item.quantity}} x $ {{cart_item}}

                </td>
                <td>
                    $ {{cart_item.sub_total}}
                </td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"> <i class="fas fa-plus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"> <i class="fas fa-minus"> </i></a>
                    &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"> <i class="fas fa-trash"></i></a>
                </td>
                {% else %}
                <td>

                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"> <i class="fas fa-minus"> </i></a>
                    &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"> <i class="fas fa-trash"></i></a>

                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>

<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
    <table class="table my_table">
        <thead class="my_table_head">
        <tr>

            <th>
                Checkout
            </th>
        </tr>

        </thead>
        <tbody>
        <tr>
            <td>
                Please review your shopping cart items before proceeding with the order payment.
            </td>

        </tr>
        <tr>
            <td class="text-left">
                Your Total is:  <strong>{{ total }}</strong>
            </td>
        </tr>
        </tbody>
    </table>
    <div class="mx-auto">
        <a href="{% url 'ecommerce_app:allProdCat' %}" class="btn btn-secondary btn-block my_button">Continue Shopping</a>
    </div>
</div>
</div>
{% endif %}
{% endblock %}

ecommerce_project/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
        WELCOME TO LULU STORE WHERE YOU CAN BUYS DIFFRENT ITEMS...
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{ category.name }}- LULU store
    {% else %}
        See our new collections
    {% endif %}
{% endblock %}
{% block content %}

{% if category %}
    <div class="">
        <div>
            <p><a href="{% url 'ecommerce_app:allProdCat' %}">Our product collections</a></p>
        </div>
    </div>
    {% endif %}
<div style=" card text-align-last: center;">
    {% if category %}
    <h1 style="text-transform: uppercase;">{{category.name}}</h1><br>
    <p>{{category.description}}</p>
    <img src="{{category.image.url}}" style="height:250px;width:250px;" alt="{{category.name}}">
</div>

    {% else %}
<div>
<img src="{% static 'img/banner.png' %}" alt="our products">
    </div>
<br>
<div>
    <h1>Our product collections</h1>
    <p>hese cases, the browser may replace the image with the text in the element's alt attribute. For these reasons and others, provide a useful value for alt whenever possible.
        indicates that this image is not a key part of the content (it's decoration or a tracking pixel), and that non-visual browsers may omit it from rendering</p>
</div>

    {% endif %}
<div class="container mt-5">
        <div class="row mx-auto">
 {% for products in products.object_list %}
<div class="col-md-4" style="width: 300px;height: 300px;">
        <a href="{{products.get_url}}"><img src="{{products.image.url}}" style="height: 180px;width:200px;" class="card-img-top" alt="{{products.name}}"></a>

         <h5 class="card-title" style="letter-spacing: 1px;">{{products.name}}</h5>
            <p class="card-text">${{products.price}}</p>

</div>

{% endfor %}

</div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}

<hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}" >{{pg}}</a>
            {% endfor %}
        </div>
  {% endif %}
    </div>
    <br>
    </div>


{% endblock %}

ecommerce_project/templates/footer.html
<footer class="bg-body-tertiary text-center text-lg-start">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2023 Copyright:
    <a class="text-body" href="#">SUHAILMK.in</a>
  </div>
  <!-- Copyright -->
</footer>

ecommerce_project/templates/header.html
{% load static %}
    <script src="https://kit.fontawesome.com/928bab6617.js" crossorigin="anonymous"></script>

<header>
        <center>
        <img src="{% static 'img/lulu_logo.png' %}" style="width:250px; height:250px;">
        </center>


</header>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><b>LULU</b></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">HOME</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ecommerce_app:allProdCat' %}">ALL PRODUCTS</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            ALL CATEGORY
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for cat in links %}
            <li><a class="dropdown-item" style="text-transform: uppercase;" href="{{cat.get_url}}">{{cat.name}}</a></li>
                 {% endfor %}
          </ul>
        </li>
        {% if item_count > 0 %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa fa-shopping-cart"></i>{{item_count}}</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

ecommerce_project/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

        {{ product.description|truncatewords:155 }}

{% endblock %}
{% block title %}
    {% if product %}
        {{ product.name }}- ABC store

    {% endif %}
{% endblock %}
{% block content %}
<div>
    <div>
        <p><a href="{% url 'ecommerce_app:allProdCat' %}">Home</a>| <a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}}</p>
    </div>
</div>
<br>
<div class="container">
    <div class="row">
            <div class="col-md-8">

    <div style="text-align: center;">
        <div>
            <img src="{{product.image.url}}" style="height:350px;width:500px;" alt="{{product.name}}">
        </div>
    </div>

            </div>
<div class="col-md-4">
    <div>
        <div>
            <h1 style="text-transform: uppercase;">{{product.name}}</h1>
            <p>${{product.price}}</p>
            <p><b>Product Description</b></p>
            <p>{{product.description}}</p>
            {% if product.stock <= 0 %}
            <p><b>Out of stock</b></p>
            {% else %}
            <a href="{% url 'cart:add_cart' product.id %}" class="btn btn-primary">Add To Cart</a>
            {% endif %}
        </div>
    </div>
    </div>
            </div>

</div>

{% endblock %}

ecommerce_project/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

        we have variety of products
{% endblock %}
{% block title %}
        Search
{% endblock %}
{% block content %}

<div>
        <p class="text-center" style="padding-top: 20px;">You have search for : <b>"{{query}}"</b></p>
</div>
<div class="container mt-5">
        <div class="row mx-auto">
 {% for products in products %}
<div class="col-md-4" style="width: 300px;height: 300px;">
        <a href="{{products.get_url}}"><img src="{{products.image.url}}" style="height: 180px;width:200px;" class="card-img-top" alt="{{products.name}}"></a>

         <h5 class="card-title" style="letter-spacing: 1px;">{{products.name}}</h5>
            <p class="card-text">${{products.price}}</p>

</div>
        </div>
</div>
        {% empty %}
        <div class="row mx-auto">
                <p class="text-center">0 result found</p>
        </div>
{% endfor %}

{% endblock %}